export const ARTWORK_PREPARATION_CONFIG = {
  analysisMaxDimension: 1600,
  borderSampleStride: 4,
  nearWhiteMinimum: 224,
  borderColourTolerance: 24,
  minimumNearWhiteBorderRatio: 0.88,
  minimumUniformBorderRatio: 0.82,
  connectedColourTolerance: 42,
  adaptiveToleranceMultiplier: 3,
  maximumConnectedTolerance: 72,
  neutralLightMinimum: 210,
  neutralChromaMaximum: 28,
  haloCleanupPasses: 2,
  lowAlphaResidualThreshold: 48,
  haloAlphaMaximum: 24,
  featherDistance: 12,
  localFeatherRadius: 1,
  boundaryDecontamination: 0.45,
  residualRectangleConfidence: 0.68,
  residualBorderBandRatio: 0.08,
  veryLightLuminance: 224,
  veryLightDarkPixelRatio: 0.08,
  cropAlphaThreshold: 8,
  cropPaddingRatio: 0.035,
  minimumCropPaddingPx: 6,
  maximumCropPaddingPx: 20,
  validationOpaqueRatio: 0.7,
  validationRectangularCoverage: 0.9,
  validationMaximumColourStdDev: 48,
} as const;

export type ArtworkPreparationConfig = typeof ARTWORK_PREPARATION_CONFIG;
